// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AdminTag             string
	IncomeAndExpenditure string
	TagGroup             string
	User                 string
	UserTag              string
}{
	AdminTag:             "admin_tag",
	IncomeAndExpenditure: "income_and_expenditure",
	TagGroup:             "tag_group",
	User:                 "user",
	UserTag:              "user_tag",
}
