// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AdminTags", testAdminTagsUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("IncomeAndExpenditures", testIncomeAndExpendituresUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("UserTags", testUserTagsUpsert)
}
