// @generated by protoc-gen-connect-web v0.8.3 with parameter "target=ts"
// @generated from file income_and_expenditure.proto (package proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteIncomeAndExpenditureRequest, DeleteIncomeAndExpenditureResponse, GetIncomeAndExpenditureRequest, GetIncomeAndExpenditureResponse, ListIncomeAndExpenditureRequest, ListIncomeAndExpenditureResponse, RegisterIncomeAndExpenditureRequest, RegisterIncomeAndExpenditureResponse, UpdateIncomeAndExpenditureRequest, UpdateIncomeAndExpenditureResponse } from "./income_and_expenditure_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.IncomeAndExpenditureService
 */
export const IncomeAndExpenditureService = {
  typeName: "proto.IncomeAndExpenditureService",
  methods: {
    /**
     * @generated from rpc proto.IncomeAndExpenditureService.ListIncomeAndExpenditure
     */
    listIncomeAndExpenditure: {
      name: "ListIncomeAndExpenditure",
      I: ListIncomeAndExpenditureRequest,
      O: ListIncomeAndExpenditureResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.IncomeAndExpenditureService.GetIncomeAndExpenditure
     */
    getIncomeAndExpenditure: {
      name: "GetIncomeAndExpenditure",
      I: GetIncomeAndExpenditureRequest,
      O: GetIncomeAndExpenditureResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.IncomeAndExpenditureService.RegisterIncomeAndExpenditure
     */
    registerIncomeAndExpenditure: {
      name: "RegisterIncomeAndExpenditure",
      I: RegisterIncomeAndExpenditureRequest,
      O: RegisterIncomeAndExpenditureResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.IncomeAndExpenditureService.UpdateIncomeAndExpenditure
     */
    updateIncomeAndExpenditure: {
      name: "UpdateIncomeAndExpenditure",
      I: UpdateIncomeAndExpenditureRequest,
      O: UpdateIncomeAndExpenditureResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.IncomeAndExpenditureService.DeleteIncomeAndExpenditure
     */
    deleteIncomeAndExpenditure: {
      name: "DeleteIncomeAndExpenditure",
      I: DeleteIncomeAndExpenditureRequest,
      O: DeleteIncomeAndExpenditureResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

