// @generated by protoc-gen-connect-web v0.8.3 with parameter "target=ts"
// @generated from file user_tag.proto (package proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteUserTagRequest, DeleteUserTagResponse, GetUserTagRequest, GetUserTagResponse, ListUserTagRequest, ListUserTagResponse, RegisterUserTagRequest, RegisterUserTagResponse, UpdateUserTagRequest, UpdateUserTagResponse } from "./user_tag_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.UserTagService
 */
export const UserTagService = {
  typeName: "proto.UserTagService",
  methods: {
    /**
     * @generated from rpc proto.UserTagService.ListUserTag
     */
    listUserTag: {
      name: "ListUserTag",
      I: ListUserTagRequest,
      O: ListUserTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserTagService.GetUserTag
     */
    getUserTag: {
      name: "GetUserTag",
      I: GetUserTagRequest,
      O: GetUserTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserTagService.RegisterUserTag
     */
    registerUserTag: {
      name: "RegisterUserTag",
      I: RegisterUserTagRequest,
      O: RegisterUserTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserTagService.UpdateUserTag
     */
    updateUserTag: {
      name: "UpdateUserTag",
      I: UpdateUserTagRequest,
      O: UpdateUserTagResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserTagService.DeleteUserTag
     */
    deleteUserTag: {
      name: "DeleteUserTag",
      I: DeleteUserTagRequest,
      O: DeleteUserTagResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

