// @generated by protoc-gen-connect-web v0.8.3 with parameter "target=ts"
// @generated from file user.proto (package proto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteUserRequest, DeleteUserResponse, GetUserRequest, GetUserResponse, LoginUserRequest, LoginUserResponse, LogoutUserRequest, LogoutUserResponse, RegisterUserRequest, RegisterUserResponse, UpdateUserRequest, UpdateUserResponse } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.UserService
 */
export const UserService = {
  typeName: "proto.UserService",
  methods: {
    /**
     * @generated from rpc proto.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserService.RegisterUser
     */
    registerUser: {
      name: "RegisterUser",
      I: RegisterUserRequest,
      O: RegisterUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UpdateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: DeleteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserService.LoginUser
     */
    loginUser: {
      name: "LoginUser",
      I: LoginUserRequest,
      O: LoginUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.UserService.LogoutUser
     */
    logoutUser: {
      name: "LogoutUser",
      I: LogoutUserRequest,
      O: LogoutUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

