// Code generated by MockGen. DO NOT EDIT.
// Source: tag_group.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/watariRyo/balance/server/proto"
)

// MockTagGroupRepository is a mock of TagGroupRepository interface.
type MockTagGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagGroupRepositoryMockRecorder
}

// MockTagGroupRepositoryMockRecorder is the mock recorder for MockTagGroupRepository.
type MockTagGroupRepositoryMockRecorder struct {
	mock *MockTagGroupRepository
}

// NewMockTagGroupRepository creates a new mock instance.
func NewMockTagGroupRepository(ctrl *gomock.Controller) *MockTagGroupRepository {
	mock := &MockTagGroupRepository{ctrl: ctrl}
	mock.recorder = &MockTagGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagGroupRepository) EXPECT() *MockTagGroupRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTagGroupRepository) Delete(ctx context.Context, input *proto.DeleteGroupRequest) (*proto.DeleteGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, input)
	ret0, _ := ret[0].(*proto.DeleteGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTagGroupRepositoryMockRecorder) Delete(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagGroupRepository)(nil).Delete), ctx, input)
}

// Get mocks base method.
func (m *MockTagGroupRepository) Get(ctx context.Context, input *proto.GetGroupRequest) (*proto.GetGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, input)
	ret0, _ := ret[0].(*proto.GetGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTagGroupRepositoryMockRecorder) Get(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTagGroupRepository)(nil).Get), ctx, input)
}

// Insert mocks base method.
func (m *MockTagGroupRepository) Insert(ctx context.Context, input *proto.RegisterGroupRequest) (*proto.RegisterGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(*proto.RegisterGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockTagGroupRepositoryMockRecorder) Insert(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTagGroupRepository)(nil).Insert), ctx, input)
}

// List mocks base method.
func (m *MockTagGroupRepository) List(tx context.Context, input *proto.ListGroupRequest) (*proto.ListGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tx, input)
	ret0, _ := ret[0].(*proto.ListGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagGroupRepositoryMockRecorder) List(tx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTagGroupRepository)(nil).List), tx, input)
}

// Update mocks base method.
func (m *MockTagGroupRepository) Update(ctx context.Context, input *proto.UpdateGroupRequest) (*proto.UpdateGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*proto.UpdateGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTagGroupRepositoryMockRecorder) Update(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagGroupRepository)(nil).Update), ctx, input)
}
